### ISSUE TITLE
It works,but I should write the URL again,again and again...

### ISSUE THREAD

**Issue by Marietto2008** [cadeyrn/newtaboverride#341] opened 2024-03-24 17:54 UTC
....as the title. What can I do to write it only the first time ? because it says that it has been modified (by what I don't know) and I should put it there too many times. This behavior is very annoying and umconfortable.

**Comment by cadeyrn** [comment] 2024-03-24 18:03
I'm afraid I don't understand what you mean. Can you please describe precisely what you are doing, what the expected result is, and what happens instead?

**Comment by Marietto2008** [comment] 2024-03-28 14:56
When I disable one extension on Firefox (and also in different circumstances that I haven't still understood),this is what happens next :

![Istantanea_2024-03-28_14-52-20](https://github.com/cadeyrn/newtaboverride/assets/755339/e71fbbfc-f987-4f5a-9106-d90cb9c21113)

**Comment by cadeyrn** [comment] 2024-04-08 19:17
Disabling an add-on removes the saved settings. This is how Firefox works and not an issue of New Tab Override.

**Comment by cadeyrn** [comment] 2024-04-09 06:27
There is no code in New Tab Override to remove any settings by itself. In fact, it uses the storage API that is intended for add-ons and used by many thousands of add-ons.

I doubt that the cause for your issue is in New Tab Override, especially since there is no similar report, but to investigate it further, it would be necessary to understand in which situation it happens.

**Comment by jnm** [comment] 2024-05-02 13:50
Hello,

I see this frequently but was always too lazy to report the issue :innocent:

On Ubuntu, with a fresh Firefox 124.0.2 (64-bit) that has no other extensions installed, if I:
1. Configure a URL in New Tab Override
2. Open a new tab to see that URL being used correctly
3. (important) Close the New Tab Override settings tab
4. Reopen New Tab Override settings

…then the URL field is blank.

Here's a screencast:
https://github.com/cadeyrn/newtaboverride/assets/2085013/7c3af88a-69e3-4a3d-b6b4-cd15e6e9831f

Thanks for the great extension. Let me know if I can provide any other useful information.

**Comment by Marietto2008** [comment] 2024-05-02 14:01
Exactly. You have explained very well the problem that I  wasn't able to explain. If you want that the address stay there forever,you can't click on the new tab override anymore. Unfortunately it happens to me some time by a mistake.

**Comment by MarcM0** [comment] 2024-06-05 17:56
I have this without even disabling the extension. Just keeps forgetting after a bit.

**Comment by clone1008** [comment] 2024-06-10 11:21
I am constantly having this problem also. Every time I open New Tab Override the URL that I have input previously is gone and I have to retype it in and close the extension.

**Comment by rursache** [comment] 2024-06-11 15:53
same issue here, i set up the start tab 15mins ago, now i had to set it up again...

**Comment by cadeyrn** [comment] 2024-06-11 18:55
The issue will be investigated for the next update.

**Closed** 2024-06-15 13:18 UTC
Labels: bug

**Comment by cadeyrn** [comment] 2024-06-15 13:47
Fixed in New Tab Override 16.0.1 and submitted to addons.mozilla.org. The update will be available soon.

**Comment by Marietto2008** [comment] 2024-06-15 14:00
Hip Hip Hurra'. Thanks.

**Comment by cadeyrn** [comment] 2024-06-20 18:25
New Tab Override 16.0.1 is available now.

**Comment by Marietto2008** [comment] 2024-06-20 19:26
bug fixed. Thanks.

Il gio 20 giu 2024, 20:25 Sören Hentzschel ***@***.***> ha
scritto:
