### ISSUE TITLE
New blank page is currently incompatible with "Set focus to URL bar"

### ISSUE THREAD

**Issue by ShalokShalom** [cadeyrn/newtaboverride#139] opened 2018-04-10 14:28 UTC
New blank page is currently incompatible with "Set focus to URL bar"

**Comment by FractalZone** [comment] 2018-05-07 07:29
It would be ideal if one option was to open the about:blank page with the cursor (focus) set to the beginning of grayed-out text such as 'Search or enter address' or 'about:blank' (?).  Right now, if I choose to use about:blank and set the focus to the address bar, the cursor is immediately after the 'k' but if I set the focus to be on the page rather than the address bar, I have to click on the address bar before entering something into it.

The most intuitive thing (IMNSHO) would be to have the cursor sitting at the beginning of the grayed-out 'Search or enter address' message that automagically disappears when one begins to make an entry into the field.  That is even more efficient than loading the Google Search page used to be before the combined address and search field in a tool bar was an option.

Regards,
FractalZ

**Comment by fabianwenk** [comment] 2018-05-10 16:26
I did just upgrade to Firefox 60.0 and I also see this behavior now. When opening a new tab the URL bar is filled with "about:blank", has the focus and the cursor is after the "k".  But when opening a new window the URL bar is empty and has the focus, as it was with new tab on Firefox 59 and before.

Best regards,
Fabian

**Comment by acatalept** [comment] 2018-05-10 17:32
I experienced the same issue as @fabianwenk after upgrading to v60.0, but found a workaround to be able to open new, blank tabs and immediately start typing search query or web address:

1. Set "Option" to "custom URL"
2. Set "URL" to a single space character (" " without quotes)

Note that after closing and reopening the New Tab Override settings, this single space has been prepended by "http://", as seen here (note the space after the slashes, but before the cursor):

![settings](https://i.imgur.com/5dqmqEi.png)

And this is the result when opening a new tab (note cursor at the beginning of the empty address bar):

![result](https://i.imgur.com/wgan4WF.png)

Behavior persists after restart -- hope this helps!

**Comment by FractalZone** [comment] 2018-05-11 02:34
That is a very useful workaround!

**Comment by ShalokShalom** [comment] 2018-05-11 06:37
Yes, I agree. It also allows to 'automatically emptying the address bar'

Its just not working here, since there is still no focus on the bar

**Comment by cadeyrn** [comment] 2018-05-11 07:00
I will investigate the issue once I have the time to do so. I have to complete some other work this week so I will probably have a look in the next week.

**Comment by est31** [comment] 2018-05-12 01:13
It sucked before this regression already. On my slow netbook, when I opened a tab using this extension, and immediately started typing the url, the url bar would be cleared out. On my fast desktop this wasn't noticeable because presumably because it cleared the url bar before I could start typing, even if I typed right away.

**Comment by cadeyrn** [comment] 2018-06-07 19:55
duplicate of #133, fixed in New Tab Override 13.0.0

**Closed by cadeyrn** 2018-06-07 19:55 UTC
Labels: investigation

**Comment by FractalZone** [comment] 2018-06-08 00:03
Sören,

Thanks taking the time to reply.  I should at least try to search for
keywords and look at the most recent threads before I post.

FractalZ

**Comment by cadeyrn** [comment] 2018-06-08 10:22
no worries, more reports are better than none. ;)

**Comment by ShalokShalom** [comment] 2018-06-08 20:46
Thanks a lot

**Comment by cadeyrn** [comment] 2018-06-09 09:33
New Tab Override 13.0.0 has been released.

**Comment by FractalZone** [comment] 2018-06-10 05:48
I think I have NTO automatically updated every time I open Firefox 62.n
(Nightly release).  I will check to make sure that is the current setting.

  There are so many new add-ons being published for Firefox these days,
many due to the horrible confusion caused by GDPR, that I just turned off
threeor more that attempt to vary how the Home or New Tab pages is loaded.
Many others offer ways to unwrap or decrypt encrypted URLs.  Using too many
of them will slow the browser to a crawl on most machines.  I am being very
picky about who is behind or wrote the code for the add-ons that could most
directly affect my privacy or system/network security, for good or for bad.

Regards,
FractalZ
