### ISSUE TITLE
Enhancement: Black backgroud

### ISSUE THREAD

**Issue by gigabit942007** [cadeyrn/newtaboverride#261] opened 2022-01-31 15:32 UTC
I use dark mode quite a lot, however, whenever i load a new tab i ALWAYS get a white flash which seems to be the extension. Could be made so there's no more flash or at least the backgroud is black? Maybe an option somewhere?

**Comment by junguler** [comment] 2022-02-25 17:32
you can apply your own styling to the page using userContent.css in firefox, just do something like this
```
@-moz-document url-prefix("moz-extension:") {
body {
background-color: rgb(34, 34, 34);
background: rgb(34, 34, 34);
background-image: linear-gradient(rgb(34, 34, 34),rgb(34, 34, 34));
color: rgb(221, 221, 221) ; }
}
```

note that this might change the appearance of other extension pages too in which case you can put the exact address of your new tab like this

```
@-moz-document domain("moz-extension://53475d7b-3160-4cec-ac0b-b64ba2912c64/html/local_file.html")
```
change the link inside the quotes to what the extensions sets 

if you want to completely remove all white flashes from firefox i made a hacky but effective workaround which you can find [here](https://github.com/junguler/firefox-dark-userContent.css)

**Comment by Gerald4000** [comment] 2022-04-13 22:15
> you can apply your own styling to the page using userContent.css in firefox

This does not work in this case with this particular extension.

Due to this extensions's mechanism, initially it loads a only some lines of javascript in a blank (white) html page.
Within this html page, the background of the body is explicitly set to 'white' by the author of this extension.

This javascript seems to load user created html and css internally and is then injecting it into the DOM of the blank page.

Thats where the flashing is coming from.

I, too, choose a dark theme for my "new tab page" and I too find this behaviour unpleasent.

**Comment by junguler** [comment] 2022-04-13 23:32
> This does not work in this case with this particular extension.

it works for me as i have a complete dark css file that i apply to all websites by default in addition of using firefox's colors options in the preferences, i didn't realize it doesn't work with the extension pages alone, regardless if you want a completely flashless firefox experience but one that alters the look of all websites you can find my css files in my github page.

i realize my answer was not a direct fix for the issue and it wasn't meant to be that way, just wanted to save some headache and eyesight fatigue from one of my fellow dark mode user.

**Comment by Gerald4000** [comment] 2022-04-14 19:48
> it works for me

No, the particular code you posted doesnt.

Unless you change additionally the browsers default behaviour globally for all other websites too by overriding their css.

This is not desired by other users.

But, I guess, you just wanted to help, which is basically a good thing ...👍

**Comment by junguler** [comment] 2022-04-14 21:44
> But, I guess, you just wanted to help, which is basically a good thing ...👍

unfortunately there is no global dark mode fix that removes all these little annoyances, i'm behind a computer all night and use a big tv as monitor so the looks have to be sacrificed to preserve sanity and eyesight, as you said it's not desired by most users and it can look quite boring applying the same color scheme to all websites but the alternative does not work for me at all

the web is a wild west and everyone is doing their own thing, i'm just thankful for firefox because they haven't locked down their browser and still allow people like me to use these kinds of methods no matter how crude and hacky they might be

**Comment by gigabit942007** [comment] 2022-04-18 11:57
So looking at these comments I have done the following:

1. Firstly locate the profile folder, open _about:profile_, click Open Folder on the line with _Profile Folder_.
2. Make folder _chrome_
3. Inside the chrome folder make a file called _userContent.css_
4. Paste the code of this comment: https://github.com/cadeyrn/newtaboverride/issues/261#issuecomment-1051052227
5. Go to _about:config_
6. Set this to true: _toolkit.legacyUserProfileCustomizations.stylesheets_

Hope this helps anyone confused about how to make this flash dissapear, thank you mozilla for being jackasses with adding a half baked dark mode.

**Comment by James-F2** [comment] 2022-06-08 14:33
I had to stop using New Tab because that darn white flash is blinding me every time I open a new tab, so annoying. :(
Needs an official fix ASAP.

**Comment by cadeyrn** [comment] 2022-06-08 14:42
There is no way to fix it within the extension. What you see is the color of browser.display.background_color in about:config. You can change it to whatever color you want.

**Comment by cadeyrn** [comment] 2022-06-14 21:31
> I dont think your last comment is correct.
>
> I have chosen a dark theme for Firefox, and in 'about:config' are two referring values stored:
>
> browser.display.background_color: #ffffff = automatically chosen for light themes
> browser.display.background_color.dark: #1C1B22 = automatically chosen for dark themes.
>
> If your statement would be true, I should see the dark color value, not a blank white page.

My comment is correct and I don't understand your example. In your example browser.display.background_color is still white so it's expected that you see the white flickering. That's the color you have to change. I never mentioned browser.display.background_color.dark.

> Indeed it seems to be the code of your extension, that is generating a blank white page
> …
>  it is your own code, that is generating this blank white page.

Nope, it's Firefox.

>  You can also see it in "/js/core/defaults.js", here is the code snippet from your extension:

The issue opener didn't mention that they use the option to only show a solid color instead of a website as new tab page. So this code is not relevant at all.

**Comment by Gerald4000** [comment] 2022-06-15 11:08
Hallo Sören,
ich schreibe auf deustch, da ich im Ausdruck sicherer bin als im Englischen.

Ich habe beide Werte-Schalter in 'about:config' für einen Test geändert.
Einmal in Grün, einmal in Violett.

Das steht auch ganz deutlich in meinem späteren Edit am Ende des Kommentares (siehe oben).

Deine Aussage scheint zumindest diesbezüglich also tatsächlich nicht korrekt.
Denn Firefox hat im Gebrauch Deines Addons weder die geänderte Hintergundfarbe fürs Standard-Theme (Grün) gezeigt, noch die fürs dunkle Theme (Violett).

Immernoch wird in Deinem Addon eine weiße, leere Seite als "Blitzer" angezeigt, bevor letzendlich das Custom-HTML von dem Addon im Browser geladen bzw gerendert wird.

Was auch immer das Problem hier ist, der von mir genannte JS-Code scheint ja nicht die Ursache zu sein, Dein Lösungsvorschlag hilft jedenfalls nicht :(


Das "weiße Blitzen" ist aber wirklich störend.
Das ist mMn keine "Randoptimierung".
Bei Verwendung dunkler Themes und in abgedunkelten Räumen, zB bei der PC-Nutzung am Abend im Wohnzimmer, ist das ständige "weiße Blitzen" während einer Surf-Session wirklich anstrengend.

Ich nutze den PC als Media-Hub auf einem großen Fernseher mit HDR und somit großer Helligkeit. Das ist jedesmal als würde ein Scheinwerfer eingeschaltet werden, der das Zimmer mit grellem Licht flutet.


**Schönen Tag und nochmal Danke für Dein Bemühen!**

**Comment by Gerald4000** [comment] 2022-06-16 13:33
Hallo Soeren.

Der Wortlaut im Eröffnungspost zum Issue ist:
> whenever i load a new tab i ALWAYS get a white flash 

Er schreibt erstmal nichts von einer geladenen Webseite.
Er erwähnt nur das öffnen eines neuen Tabs.

Und dieser geschilderte "weiße Blitzer" beim Öffnen eines neuen Tabs ist genau das gleiche Problem, auf das auch ich mich beziehe.
.


Welches Missverständnis gibt es hier?
Ich würde es gerne beseitigen.

Bei mir werden die Farben, die in "about:config" hinterlegt wurden, nicht gezeigt.
Es bleibt bei genau diesem geschilderten "weißen Blitzer".

Um zu zeigen wie krass der Effekt ist, hier ein Video auf dem Bilderdienst imgur:
https://imgur.com/a/RHfx3jI

Da die Augen am Abend auf die dunklere Umgebung im Wohnzimmer eingestellt sind, ist das kurze, grelle Aufblitzen echt unangenehm. 

Die Farben Grün und Violett sind zum Testen übrigens zum Zeitpunkt des Videos in "about:config" hinterlegt.

.
**Nochmals Danke für Dein Bemühen!**

**Comment by cadeyrn** [comment] 2022-06-16 20:23
> Er schreibt erstmal nichts von einer geladenen Webseite.
> Er erwähnt nur das öffnen eines neuen Tabs.

Standard bei Verwendung der Erweiterung ist das Öffnen einer Website in einem neuen Tab. Wenn nichts anderes angegeben wird, ergibt es für mich keinen Sinn, etwas anderes anzunehmen als die Standard-Einstellung. Und da wird kein HTML der Erweiterung geladen und die genannte Einstellung greift.

> Um zu zeigen wie krass der Effekt ist, hier ein Video auf dem Bilderdienst imgur:
> https://imgur.com/a/RHfx3jI

Du nutzt offensichtlich die Option für die Verwendung einer lokalen Datei. Das ändert die Situation. Daher auch der Vorschlag, ein eigenes Issue zu eröffnen. Ein Workaround wäre jedenfalls die Verwendung eines lokalen Servers, beispielsweise über XAMPP. Das ist kein großer Aufwand und dann kann die Option zum Laden einer Website genutzt werden, um die lokale Datei aufzurufen.

**Comment by Gerald4000** [comment] 2022-06-17 09:39
Guten Morgen Sören.

Richtig ist, das ich ein eigenes HTML nutze, dass von deinem Addon in den EInstellungen bei Optionswahl eingelesen wird.

Nicht richtig ist, das der gezeigte Effekt bei "geladenen, externen Websites" durch die empfohlenen Schalter in "about:config" abzustellen sei.

Für einen Test habe ich die Hintergund-Farben angepasst und eine beliebige Nachrichten-Website als "New Tab" in Deiner Erweiterung eingetragen.

Der weiße Blitzer bleibt leider ... :( 

Hier ein Video, dass den Blitzer als auch alle erwähnten Einstellungen kurz zeigt:
https://imgur.com/a/Ykl72ly

.
Grüße & Danke!

**Comment by cadeyrn** [comment] 2022-06-17 14:15
> Nicht richtig ist, das der gezeigte Effekt bei "geladenen, externen Websites" durch die empfohlenen Schalter in "about:config" abzustellen sei.

Bei mir funktioniert das schon seit Jahren und auf mehr als nur einem Gerät so.

> Für einen Test habe ich die Hintergund-Farben angepasst

Ich verstehe nicht, wieso du immer noch zwei Schalter anpasst, nachdem ich schon mehrmals sagte, dass nur ein einziger Schalter anzupassen ist.

> Wenn ich Dein Addon ausschalte und einen neuen Tab durch regulären, mittleren Maus-Klick öffne, dann wird kein weißer Blitzer angezeigt. Es scheint also doch irgendwie an Deinem Addon zu liegen.

Nein. Da die Erweiterung nichts anderes macht, als einen neuen Tab zu öffnen, kann die Ursache überhaupt nicht im Add-on liegen.

Und das Flackern kann man durchaus auch ohne Erweiterung feststellen, auch wenn es schwieriger zu reproduzieren ist, weil es unzuverlässiger auftritt (was Sinn ergibt, da ein Schritt wegfällt und Firefox dann meistens schnell genug ist). Aber das Flackern kommt wie gesagt nicht von der Erweiterung. Die Erweiterung macht es höchstens sichtbarer auf Grund der Funktionsweise.

> Auch bei deaktiviertem Addon wird die per "about:config" gesetzte Hintergrund-Farbe nicht übernommen. Statt eines eingestellten Violett wird das dunkle Grau des Default-Themes gezeigt.

Das unterstreicht, was ich schrieb. Denn dann hast du das Problem auch ohne meine Erweiterung. Wenn du about:blank in die Adressleiste eingibst, müsstest du die Farbe sehen. Und technisch ist about:blank beim Laden von Websites immer involviert, daher das Flackern, wenn Firefox nicht schnell genug ist.

**Comment by ADTC** [comment] 2023-05-07 16:36
I don't know any German. Please, could you fix this somehow?

**Comment by cadeyrn** [comment] 2023-05-07 17:15
@ADTC There is nothing to fix within New Tab Override. As I already wrote last year:

> There is no way to fix it within the extension. What you see is the color of browser.display.background_color in about:config. You can change it to whatever color you want.

**Comment by ADTC** [comment] 2023-05-07 18:37
As an example, here's a random website which now has a red background because I changed that preference in `about:config` to `#FF0000`. (You can also reproduce the same problem by creating a simple HTML file and opening it.)

<img width="643" alt="image" src="https://user-images.githubusercontent.com/6047296/236696063-21a57e85-3db2-46f1-be87-671d323c4397.png">

That's why it's not acceptable to simply set that preference as a fix for this problem. It applies globally to all websites and pages where a background is not specified. The extension should be fixed within, or a better solution that only targets the extension should be provided.

Thank you again, for taking another look at this issue. ❤️

**Comment by ADTC** [comment] 2023-05-08 08:55
Just an update that Firefox Stable doesn't allow me to continue using the modified extension as it fails signing. [I will have to switch to Developer Edition,](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users) which I don't want to do. I hope the original signed extension will have a good fix soon. Thank you.

[screenshot for reference](https://user-images.githubusercontent.com/6047296/236779331-93632bc6-01a5-4a38-9977-3455c0f5dbcc.png) (color warning: has a red band)

**Comment by cadeyrn** [comment] 2023-05-08 09:55
@ADTC Thank you for your investigation. I will apply this fix in the next update of New Tab Override if I don't find any issues during testing.

**Comment by cadeyrn** [comment] 2023-05-24 18:40
Sorry, due to a medical emergency of my girlfriend it will have to wait a bit more. I hope to get to it soon.

**Comment by ADTC** [comment] 2023-05-24 23:56
I hope and wish for your girlfriend to get well soon! Please take your time to be with your family. Thank you for your contributions to open source. :)

**Closed** 2024-02-03 15:03 UTC
Labels: enhancement
