### ISSUE TITLE
Problem with Firefox 60 and about:blank

### ISSUE THREAD

**Issue by olauer** [cadeyrn/newtaboverride#144] opened 2018-05-15 08:48 UTC
Using empty page (about:blank) with Firefox 60 now there is written about:blank in address bar. In Firefox 59 with the same settings, address bar was empty.
So now simply opening a new tab and writing a new address leads to strange results as about:blank is "added" in front. You always have to click into address bar and overwrite the current setting

**Comment by Der-Dings** [comment] 2018-05-15 09:48
From the newtaboverride settings page:

> Automatic emptying of the address bar or marking of the URL is currently not possible for WebExtensions. This requires a change from Mozilla.

My quick and dirty fix: use "user defined URL" and set the URL to a single blank sign. Not very nice, but it works for me.

**Comment by nickpainter** [comment] 2018-05-23 14:15
Just enter a single space within the "user defined URL" textbox.  Firefox will automatically trim the white space if you immediately begin typing a URL after opening a new tab.

**Comment by PixelEater** [comment] 2018-05-24 05:11
That certainly is a dirty fix, but I'd like to confirm that somehow it is working in tandem with Tree Style Tab if I leave "Guess a newly opened tab" set to about:blank, which I take to mean underneath it all this fix actually still loads some aspect of about:blank. Thanks both of you for outlining it, I was definitely stumbling over learning to ctrl+a the URL field by habit. Only other tradeoff I'm seeing for now is the actual title of the tab will not be New Tab and of course this extension gets mentioned to the left of the URL field.

**Comment by cadeyrn** [comment] 2018-06-07 19:56
duplicate of #133, fixed in New Tab Override 13.0.0, will be released soon.

**Closed by cadeyrn** 2018-06-07 19:56 UTC

**Comment by cadeyrn** [comment] 2018-06-09 09:31
New Tab Override 13.0.0 has been released.
