### ISSUE TITLE
When the "focus web page" option is enabled it is not possible to click on the "Your new tab has changed" dialog.

### ISSUE THREAD

**Issue by Blast-City** [cadeyrn/newtaboverride#224] opened 2020-09-30 13:48 UTC
1- Disable the New Tab Override extension.
2- Enable the New Tab Override making sure that the "Focus Web Page" option is enabled.
3- Press the New Tab button (+).

**Result:** The "Your new tab has changed" dialogue disappears without any user action. This doesn't seem to happen when Ctrl+T is used instead of the new tab button or if the "Focus Web Page" option is disabled.

**Comment by cadeyrn** [comment] 2021-05-13 12:57
I cannot reproduce. Maybe it was an issue that was fixed in the meantime? If you still can reproduce please open a new issue. Thanks!

**Closed by cadeyrn** 2021-05-13 12:57 UTC
