### ISSUE TITLE
[Feature request] Cache webpage do not load it every time

### ISSUE THREAD

**Issue by aaronrancsik** [cadeyrn/newtaboverride#208] opened 2020-06-13 22:16 UTC
Hello, 
First of all thanks for the nice work. 
I have a feature request. 
Please cache the selected webpage and do not load it every time it would be a much smoother experience. 
When I click to new tab it always load it and for a searx instance  it takes a while like 0.3 sec and it is annoying.
Thanks again!

**Comment by cadeyrn** [comment] 2020-08-03 13:27
Duplicate of #145.

**Closed by cadeyrn** 2020-08-03 13:27 UTC
